name: JSON Schema Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Clone test suite
        run: git clone https://github.com/json-schema-org/JSON-Schema-Test-Suite.git

      - name: Install dependencies
        run: pip install -v .

      - name: Run tests
        working-directory: json_test_suite
        run: |
          cargo run --release --  --root-dir "../JSON-Schema-Test-Suite" --output-path "test_suite_results.json"
          cat test_suite_results.json

